frr version 10.5.3_git
frr defaults traditional
hostname pe2
no ipv6 forwarding
!
interface eth1
 ip address 10.23.0.3/24
exit
!
interface eth2
 ip address 192.168.100.1/24
exit
!
router ospf
 network 10.23.0.0/24 area 0
 network 192.168.100.0/24 area 0
exit
!
end
