frr version 10.5.3_git
frr defaults traditional
hostname router1
no ipv6 forwarding
!
!
interface eth1
 ip address 192.168.2.254/24
exit
!
interface eth2
 ip address 10.23.0.3/24
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router ospf
 network 10.0.0.0/8 area 0.0.0.0
 network 192.168.2.0/24 area 0.0.0.0
exit
!
